### ISSUE TITLE
payeezy dead?

### ISSUE THREAD

**Issue by pivotal-globehealer** [payeezy/payeezy_direct_API#16]
We just implemented payeezy for a react application with a rails backend. We used payeezy js for getting the token, which sends the token to rails which uses the payeezy ruby library to make a payment.

We are receiving success and transaction numbers for the payments in the sandbox environment. We wanted to see the transactions in a web interface so that we can demonstrate to our product owner that we have successfully integrated with payeezy. 

We could not find that interface and called support (1.855.799.0790). They indicated that this product should not be used for web transactions. They steered us to the payeezy gateway api. The payeezy documentation is not forthcoming about this distinction and we were checking in to see if this is still a supported product.

**Comment by davidadas** [comment]
I'm...not entirely sure why they said that.  I've used this before and it's been fine for prod.  I've used it with Node, though.

**Comment by lukevp** [comment]
They're renaming payeezy to Clover, but the JS interface was recommended to us for a new engagement, so I would not say that it's dead.  Not sure if you've seen the JS but it's not very complicated.  There's not really much need for a project like this to be active once a working version is completed.

**Comment by pivotal-globehealer** [comment]
We were able to successfully integrate. Looks like the first line support
was giving out incorrect information.

I was troubled that this github report isn't very active.

After getting a signed contract, you will need to have the developer
account linked to the merchant account.

**Comment by morenoh149** [comment]
@lukevp I just reviewed the open PRs. Some of them are good changes. They should be merged.
