### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by jabrego** [payeezy/payeezy_direct_API#2]
Hello,

I am trying to use the direct API for php. However, when I require "PayeezyTest.php" in another file the following error appears.

Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in C:\wamp\www\payeezy_php\example\tests\PayeezyTest.php on line 34

Am I missing something?

Thanks for your time.

**Comment by nohup-atulparmar** [comment]
Hello jabrego, I did corrected the compilation error. Please try now. 
Note: that you may need PHPUnit_Framework_TestCase to run the testcase.
