### ISSUE TITLE
"payment_method_missing"

### ISSUE THREAD

**Issue by jaenelleisidro** [payeezy/payeezy_direct_API#5]
Hi,

my Payeezy is throwing an error “payment method is missing” 

here’s my code

http://pastebin.com/gEyAfyuf

here’s the response on our site at http://wolcottschoolpay.com/test/payeezy_php/test.php

{
correlation_id: "228.1440254919101",
Error: 
{
messages: 
[
{
code: "payment_method_missing",
description: "The payment method is missing"
},
{
code: "missing_amount",
description: "The amount is missing"
},
{
code: "missing_currency",
description: "The currency is missing"
}
]
},
transaction_status: "Not Processed",
validation_status: "failed",
transaction_type: "authorize",
currency: "USD”
}

I copied most of the part here on the official payeezy php direct library on github.
https://github.com/payeezy/payeezy_direct_API/blob/master/payeezy_php/example/tests/PayeezyTest.php

i also tried both my merchant test details and the one provided at payeezy library but none worked.

Is this a library issue? any idea?

**Comment by nohup-atulparmar** [comment]
Corrected card_expiry , and added amount and currency_code

Please try following: 


<?php
require_once('./Payeezy.php');
$payeezy = new Payeezy();

 
//test account provided in sample code
$payeezy->setApiKey("y6pWAJNyJyjGv66IsVuWnklkKUPFbb0a");
$payeezy->setApiSecret("86fbae7030253af3cd15faef2a1f4b67353e41fb6799f576b5093ae52901e6f7");
$payeezy->setMerchantToken("fdoa-a480ce8951daa73262734cf102641994c1e55e7cdf4c02b6");
 
 
$payeezy->setTokenUrl("https://api-cert.payeezy.com/v1/transactions/tokens");  
$payeezy->setUrl("https://api-cert.payeezy.com/v1/transactions");
 
 
 
 
$response=$payeezy->authorize(setTokenPayload());
echo $response;
 
function setTokenPayload(){
 
    $card_holder_name = $amount = $transaction_type = $auth = $card_number = $ta_token = $card_type = $card_cvv = $card_expiry = $currency_code = $merchant_ref="";
   
    $transaction_type = processInput("FDToken");
    $auth = processInput("false");
    $ta_token = processInput("NOIW");
 
    $card_holder_name = processInput("John Smith");
    $card_number = processInput("4788250000028291");
    $card_type = processInput("visa");
    $card_cvv = processInput("123");
    $card_expiry = processInput("1230");
    $currency_code = processInput("USD");
    $amount = processInput("1000");
    $merchant_ref = processInput("Astonishing-Sale");
    
 
    $getTokenPayload = array(
 
        "type"=> $transaction_type,
        "auth" => $auth,
        "ta_token" => $ta_token,
        "card_type" => $card_type,
        "card_holder_name" => $card_holder_name,
        "card_number" => $card_number,
        "card_expiry" => $card_expiry,
        "card_cvv" => $card_cvv,
        "amount"=> $amount,
        "currency_code"=> $currency_code,
    );
 
    return $getTokenPayload;
 
}
 
function processInput($data) {
        $data = trim($data);
        $data = stripslashes($data);
        $data = htmlspecialchars($data);
        return strval($data);
}
 
?>

**Comment by nohup-atulparmar** [comment]
Please let us know if you have any questions.

**Comment by nohup-atulparmar** [comment]
Closing
